version: 2
jobs:
  build:
    working_directory: ~/jheadx
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Installing jhead...
          command: sudo apt-get update && sudo apt-get install -y jhead
      # Download and cache dependencies
      - restore_cache:
          keys:
            - jheadx-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - jheadx-dependencies-
      - run:
          name: Installing...
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: jheadx-dependencies-{{ checksum "package.json" }}
      - run:
          name: Building...
          command: npm run build
      - run:
          name: Testing...
          command: npm run test
